# The main config file for your Jekyll template

# Site settings
title: EnthusiastiCon               # used for the html title of every page
desc: >
  A software engineering conference taking place in Berlin this March!

url: http://zormit.github.io      # put your website hosting url here
baseurl: '/enthusiasticon-eventpage'     # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: info@enthusiasticon.de
author: EnthusiastiCon
twitter_username:
github_username:

# Put your ga tracking code below
google_analytics: ''

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
    desc: Learn about us
  - title: Call for Proposals
    url: /cfp/
    desc: Submit a talk!
  - title: Code of Conduct
    url: /coc/
    desc: Our code of conduct

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
